### ISSUE TITLE
Newbe user question.

### ISSUE THREAD

**Issue by eriknyk** [wycats/javascript-decorators#16]
how I can you in a script using node.
by example, I have:

``` javascript
// index.js
// Register babel to have ES6 support on the server
require('babel/register');

require('./test');
```

and the file 

``` javascript
// test.js

// A simple decorator
@annotation
class MyClass { 
    constructor () {
        this.annotated = false;
    }
}

function annotation(target) {
   // Add a property on target
   target.annotated = true;
}
```

and run it

``` bash
$ node index.js
```

I got:

``` bash
Unexpected token (3:0)
  1 |
  2 | // A simple decorator
> 3 | @annotation
    | ^
  4 | class MyClass {
  5 |     constructor () {
  6 |         this.annotated = false;
    at Parser.pp.raise (/Users/erik/es7-experimental/node_modules/babel/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.unexpected (/Users/erik/es7-experimental/node_modules/babel/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseDecorator (/Users/erik/es7-experimental/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:146:10)
    at Parser.pp.parseDecorators (/Users/erik/es7-experimental/node_modules/babel/node_modules/babel-core/lib/acorn/src/statement.js:132:31)
```

Please help me how to enable annotation support to babel, to run this example.

Regards.

**Comment by jamiebuilds** [comment]
@eriknyk Please direct this question towards Babel. You can go ask in the [Babel support chat](https://gitter.im/babel/babel).

**Comment by eriknyk** [comment]
thanks, I found help there!
